include:
  - project: "tychodev1/gitlab-coe/pipeline-templates"
    file: "/templates/Build-Image.gitlab-ci.yml"
    ref: main

variables:
  BUILD_IMAGE: "true"
  CONTAINER_RELEASE_IMAGE: $CI_PROJECT_NAME-3.9:latest
